name: CI

on: 
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: recursive
      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
